apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
     "krateo.io/connector-verbose": "true"
  name: example-pricing-vm-azure
  namespace: krateo-system
spec:
  chart:
    repo: example-pricing-vm-azure
    url: https://charts.krateo.io
    version: "0.1.0"
---
apiVersion: composition.krateo.io/v0-1-0
kind: FocusDataPresentationAzure
metadata:
  name: finops-example-azure-vm-pricing
  namespace: krateo-system
spec:
  annotationKey: krateo-finops-focus-resource
  filter: serviceName eq 'Virtual Machines' and skuId eq 'DZH318Z0K9JH/00KX' and armRegionName eq 'westus3' and type eq 'Consumption'
  scraperConfig:
    tableName: pricing_table
    pollingIntervalHours: 1
    scraperDatabaseConfigRef: 
      name: finops-database-handler
      namespace: krateo-system