apiVersion: compute.azure.com/v1api20220301
kind: VirtualMachine
metadata:
  name: aso-sample-vm
  annotations: 
    focus-resource-name: '["DZH318Z0K9JH/00KX"]'
spec:
  hardwareProfile:
    vmSize: Standard_B2ats_v2
  location: {{ .Values.armRegionName }}
  networkProfile:
    networkInterfaces:
    - reference:
        group: network.azure.com
        kind: NetworkInterface
        name: {{ include "example-pricing-vm-azure.fullname" . }}
  osProfile:
    adminPassword:
      key: password
      name: aso-vmsecret
    adminUsername: adminUser
    computerName: poppy
  owner:
    name: {{ .Values.resourceGroupName }}
  storageProfile:
    imageReference:
      publisher: Canonical
      offer: 0001-com-ubuntu-server-jammy
      sku: 22_04-lts
      version: latest
---
apiVersion: composition.krateo.io/v0-1-0
kind: FocusDataPresentation
metadata:
  name: {{ include "example-pricing-vm-azure.fullname" . }}
spec:
  filter: serviceName eq 'Virtual Machines' and skuId eq 'DZH318Z0K9JH/00KX' and armRegionName eq '{{ .Values.armRegionName }}' and type eq 'Consumption'
  scraperConfig:
    tableName: pricing_table
    pollingIntervalHours: 1
    scraperDatabaseConfigRef: 
      name: finops-tutorial-config
      namespace: krateo-system