apiVersion: compute.azure.com/v1api20220301
kind: VirtualMachine
metadata:
  name: aso-sample-vm
  annotations: 
    krateo-finops-focus-resource: '["DZH318Z0K9JH/00KX"]'
spec:
  hardwareProfile:
    vmSize: Standard_B2ats_v2
  location: {{ .Values.armRegionName }}
  networkProfile:
    networkInterfaces:
    - reference:
        group: network.azure.com
        kind: NetworkInterface
        name: {{ include "example-pricing-vm-azure.fullname" . }}
  osProfile:
    adminPassword:
      key: password
      name: aso-vmsecret
    adminUsername: adminUser
    computerName: poppy
  owner:
    name: {{ .Values.resourceGroupName }}
  storageProfile:
    imageReference:
      publisher: Canonical
      offer: 0001-com-ubuntu-server-jammy
      sku: 22_04-lts
      version: latest